name = "remix-cloudflare-workers"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]
  CLERK_AFTER_SIGN_IN_URL = "/"
  CLERK_AFTER_SIGN_UP_URL = "/"
  CLERK_SIGN_IN_URL = "/signin"
  CLERK_SIGN_UP_URL = "/signup"
